name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install pip
      run: 
        python -m pip install --upgrade pip
    - name: Install dependencies
      run:
        pip install -r requirements.txt
    - name: install flake8
      run:
        pip install flake8      
    - name: Lint with flake8
      run: 
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Install package
      run: |
        python setup.py install
    - name: Test with unittest
      working-directory: ./tests
      run:
        python -m unittest tests.py
    - name: Lint with flake8
      run:
        # lint everything
        flake8 . --count --show-source --statistics